on: 
  issue_comment:
    types: [created]

jobs:
  fast_forward_job:
    name: Fast Forward
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/fast-forward')   
    runs-on: ubuntu-latest
    steps:
      - name: Fast Forward action
        id: ff-action
        uses: endre-spotlab/fast-forward-js-action@1.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          success_message: 'Success! Fast forwarded ***target_base*** to ***source_head***! ```git checkout target_base && git merge source_head --ff-only``` '
          failure_message: 'Failed!  Possible reasons: 1) Cannot do a fast forward, ***source_head*** is not ahead of ***target_base*** 2) Review is required 3) Other status checks are failing '
